version: "3"
services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DEBUG=true
      - BOLT_PATH=/data/db/cake-chicken.db
      - SECRET=12345
    volumes:
      - db-data:/data/db
volumes:
  db-data: