[metadata.heroku]
  root-package = "gitlab.com/petrrusanov/cake-chicken"
  go-version = "1.13"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/hashicorp/logutils"
  version = "1.0.0"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  branch = "master"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "1.0.1"
