[metadata.heroku]
  root-package = "gitlab.com/boilerplate/backend"
  go-version = "1.13"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/hashicorp/logutils"
  version = "1.0.0"

[[constraint]]
  name = "github.com/jessevdk/go-flags"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/globalsign/mgo"

[[constraint]]
  name = "github.com/go-pkgz/mongo"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "1.0.1"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.0.0"
